In [1]:
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# -------------------------------------------------
# Create FrozenLake Environment
# -------------------------------------------------
env_desc = [
    "SFFF",
    "FHFH",
    "FFFH",
    "HFFG"
]

env = gym.make("FrozenLake-v1", desc=env_desc, is_slippery=True)


In [3]:
def value_iteration(env, gamma=0.99, theta=1e-8):

    n_states = env.observation_space.n
    n_actions = env.action_space.n

    V = np.zeros(n_states)
    iteration = 0

    while True:
        delta = 0
        new_V = np.zeros(n_states)

        for s in range(n_states):

            action_values = []

            for a in range(n_actions):

                value = 0

                for probability, next_state, reward, terminated in env.unwrapped.P[s][a]:

                    value += probability * (
                        reward + gamma * V[next_state] * (not terminated)
                    )

                action_values.append(value)

            new_V[s] = max(action_values)

            delta = max(delta, abs(new_V[s] - V[s]))

        V = new_V
        iteration += 1

        if delta < theta:
            break

    # Find optimal policy
    policy = np.zeros(n_states, dtype=int)

    for s in range(n_states):

        action_values = []

        for a in range(n_actions):

            value = 0

            for probability, next_state, reward, terminated in env.unwrapped.P[s][a]:

                value += probability * (
                    reward + gamma * V[next_state] * (not terminated)
                )

            action_values.append(value)

        policy[s] = np.argmax(action_values)

    return V, policy, iteration

In [4]:
# -------------------------------------------------
# Run Value Iteration
env = gym.make("FrozenLake-v1", is_slippery=False)

V, policy, iterations = value_iteration(env)

In [5]:

# -------------------------------------------------
# Display Output
# -------------------------------------------------
print("Name:Niralya J")
print("Register Number:212224230188")
print("Value Iteration Completed")
print("Number of Iterations:", iterations)

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(4, 4), 4))


action_symbols = {
    0: "L",
    1: "D",
    2: "R",
    3: "U"
}

policy_grid = np.array(
    [action_symbols[action] for action in policy]
).reshape(4, 4)

print("\nOptimal Policy:")
print(policy_grid)
env.close()

Name:Niralya J
Register Number:212224230230
Value Iteration Completed
Number of Iterations: 7

Optimal State-Value Function:
[[0.951  0.9606 0.9703 0.9606]
 [0.9606 0.     0.9801 0.    ]
 [0.9703 0.9801 0.99   0.    ]
 [0.     0.99   1.     0.    ]]

Optimal Policy:
[['D' 'R' 'D' 'L']
 ['D' 'L' 'D' 'L']
 ['R' 'D' 'D' 'L']
 ['L' 'R' 'R' 'L']]


In [11]:
# -------------------------------------------------
# Create FrozenLake Environment
# -------------------------------------------------

env_desc1 = [
    "SFFFF",
    "FFFHF",
    "HFHFF",
    "FHFHF",
    "FHFFG"
]

env1 = gym.make(
    "FrozenLake-v1",
    desc=env_desc1,
    is_slippery=True
)

In [12]:
# -------------------------------------------------
# Value Iteration Algorithm
# -------------------------------------------------

def value_iteration(env1, gamma=0.99, theta=1e-8):
    """
    Performs value iteration and returns
    the optimal value function and policy.
    """

    n_states = env1.observation_space.n
    n_actions = env1.action_space.n

    # Initialize value function
    V = np.zeros(n_states)

    iteration = 0

    while True:

        delta = 0

        for s in range(n_states):

            action_values = []

            for a in range(n_actions):

                value = 0

                for probability, next_state, reward, terminated in env1.unwrapped.P[s][a]:

                    value += probability * (
                        reward +
                        gamma * V[next_state] * (not terminated)
                    )

                action_values.append(value)

            # Bellman Optimality Equation
            new_value = max(action_values)

            delta = max(delta, abs(new_value - V[s]))

            V[s] = new_value

        iteration += 1

        if delta < theta:
            break

    # -------------------------------------------------
    # Extract Optimal Policy
    # -------------------------------------------------

    policy = np.zeros(n_states, dtype=int)

    for s in range(n_states):

        action_values = []

        for a in range(n_actions):

            value = 0

            for probability, next_state, reward, terminated in env1.unwrapped.P[s][a]:

                value += probability * (
                    reward +
                    gamma * V[next_state] * (not terminated)
                )

            action_values.append(value)

        policy[s] = np.argmax(action_values)

    return V, policy, iteration

In [13]:
# -------------------------------------------------
# Run Value Iteration
# -------------------------------------------------

V, policy, iterations = value_iteration(env1)

In [14]:
# -------------------------------------------------
# Display Output
# -------------------------------------------------

print("Name: Niralya J")
print("Register Number: 212224230188")
print("Value Iteration Completed")
print("Number of Iterations:", iterations)

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(5, 5), 4))

action_symbols = {
    0: "L",
    1: "D",
    2: "R",
    3: "U"
}

policy_grid = np.array(
    [action_symbols[action] for action in policy]
).reshape(5, 5)

print("\nOptimal Policy:")
print(policy_grid)

env1.close()

Name: Niralya J
Register Number: 212224230188
Value Iteration Completed
Number of Iterations: 278

Optimal State-Value Function:
[[0.5824 0.6    0.6358 0.6909 0.767 ]
 [0.5315 0.4967 0.3737 0.     0.7902]
 [0.     0.1639 0.     0.2763 0.8374]
 [0.     0.     0.1359 0.     0.91  ]
 [0.     0.     0.4119 0.7004 0.    ]]

Optimal Policy:
[['U' 'U' 'U' 'U' 'R']
 ['U' 'U' 'L' 'L' 'R']
 ['L' 'L' 'L' 'D' 'R']
 ['L' 'L' 'L' 'L' 'R']
 ['L' 'L' 'R' 'D' 'L']]
